name: BumpVersion

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  bump_version:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 15.10.0 ]
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.3.0
        with:
          node-version: ${{ matrix.node-version }}
      - name: Bump version
        run: |
          git config --global user.email "LZygmunt-BumperBot@user.noreply.github.com"
          git config --global user.name "LZygmunt-BumperBot"
          npm run bump
          git push --follow-tags --no-verify
