# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  workflow:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 15.10.0 ]
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.3.0
        with:
          node-version: ${{ matrix.node-version }}
      # Runs a single command using the runners shell
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(TZ=Europe/Warsaw date +'%Y-%m-%d %H:%M:%S')"
      - name: Echo date
        run: echo ${{ steps.date.outputs.date }}
      - name: Bump version
        run: npm run bump
